src/Entity/Livre.php
<?php

namespace App\Entity;

use App\Repository\LivreRepository;
use Doctrine\Common\Collections\ArrayCollection;
use Doctrine\Common\Collections\Collection;
use Doctrine\ORM\Mapping as ORM;
use Symfony\Component\Validator\Constraints as Assert;

#[ORM\Entity(repositoryClass: LivreRepository::class)]
class Livre
{
    #[ORM\Id]
    #[ORM\GeneratedValue]
    #[ORM\Column(type: 'integer')]

    private $id;

    #[Assert\Isbn(
        type: Assert\Isbn::ISBN_13,
        message: 'This value is not valid.',
    )]
    #[ORM\Column(type: 'string', length: 13)]
    private $isbn;

    #[ORM\Column(type: 'string', length: 255)]
    private $titre;

    #[Assert\Positive]
    #[ORM\Column(type: 'smallint')]
    private $nombre_pages;

    #[ORM\Column(type: 'date')]
    private $date_de_parution;

    #[Assert\Range(
        min: 0,
        max: 20,
        notInRangeMessage: 'Note must be between {{ min }} and {{ max }}',
    )]
    #[ORM\Column(type: 'integer', nullable: true)]
    private $note;

    #[ORM\ManyToMany(targetEntity: Auteur::class, inversedBy: 'livres')]
    private $auteurs;

    #[ORM\ManyToMany(targetEntity: Genre::class, inversedBy: 'livres')]
    private $genres;

    public function __construct()
    {
        $this->auteurs = new ArrayCollection();
        $this->genres = new ArrayCollection();
    }

    public function getId(): ?int
    {
        return $this->id;
    }

    public function getIsbn(): ?string
    {
        return $this->isbn;
    }

    public function setIsbn(string $isbn): self
    {
        $this->isbn = $isbn;

        return $this;
    }

    public function getTitre(): ?string
    {
        return $this->titre;
    }

    public function setTitre(string $titre): self
    {
        $this->titre = $titre;

        return $this;
    }

    public function getNombrePages(): ?int
    {
        return $this->nombre_pages;
    }

    public function setNombrePages(int $nombre_pages): self
    {
        $this->nombre_pages = $nombre_pages;

        return $this;
    }

    public function getDateDeParution(): ?\DateTimeInterface
    {
        return $this->date_de_parution;
    }

    public function setDateDeParution(\DateTimeInterface $date_de_parution): self
    {
        $this->date_de_parution = $date_de_parution;

        return $this;
    }

    public function getNote(): ?int
    {
        return $this->note;
    }

    public function setNote(?int $note): self
    {
        $this->note = $note;

        return $this;
    }

    /**
     * @return Collection|Auteur[]
     */
    public function getAuteurs(): Collection
    {
        return $this->auteurs;
    }

    public function addAuteur(Auteur $auteur): self
    {
        if (!$this->auteurs->contains($auteur)) {
            $this->auteurs[] = $auteur;
            $auteur->addLivre($this);
        }

        return $this;
    }

    public function removeAuteur(Auteur $auteur): self
    {
        if ($this->auteurs->removeElement($auteur)) {
            $auteur->removeLivre($this);
        }

        return $this;
    }

    /**
     * @return Collection|genre[]
     */
    public function getGenres(): Collection
    {
        return $this->genres;
    }

    public function addGenre(genre $genre): self
    {
        if (!$this->genres->contains($genre)) {
            $this->genres[] = $genre;
        }

        return $this;
    }

    public function removeGenre(genre $genre): self
    {
        $this->genres->removeElement($genre);

        return $this;
    }

    public function __toString()
    {
        return $this->titre;
    }
}

templates/base.html.twig
<!DOCTYPE html>
<html>
	<head>
		<meta charset="UTF-8">
		<title>
			{% block title %}Welcome!
			{% endblock %}
		</title>
		<link
		rel="icon" href="{{asset ('images/icon.png') }}">
		{# Run `composer require symfony/webpack-encore-bundle` to start using Symfony UX #}
		{% block stylesheets %}
			<link rel="stylesheet" href="https://cdnjs.cloudflare.com/ajax/libs/twitter-bootstrap/5.0.1/css/bootstrap.min.css">
			<link rel="stylesheet" href="https://cdn.datatables.net/1.11.3/css/dataTables.bootstrap5.min.css">
			<link href="https://cdn.jsdelivr.net/npm/bootstrap@5.0.2/dist/css/bootstrap.min.css" rel="stylesheet" integrity="sha384-EVSTQN3/azprG1Anm3QDgpJLIm9Nao0Yz1ztcQTwFspd3yD65VohhpuuCOmLASjC" crossorigin="anonymous">
			<link rel="stylesheet" href="https://cdn.jsdelivr.net/npm/bootstrap-icons@1.7.2/font/bootstrap-icons.css">
			<link rel="stylesheet" href="{{ asset('css/base.css') }}">

			{{ encore_entry_link_tags('app') }}
		{% endblock %}
		{% block style %}{% endblock %}


		{% block javascripts %}

			<script src="https://code.jquery.com/jquery-3.5.1.js"></script>

			<script src="https://cdn.datatables.net/1.11.3/js/jquery.dataTables.min.js"></script>

			<script src="https://cdn.datatables.net/1.11.3/js/dataTables.bootstrap5.min.js"></script>

			<script src="https://cdn.jsdelivr.net/npm/bootstrap@5.0.2/dist/js/bootstrap.bundle.min.js" integrity="sha384-MrcW6ZMFYlzcLA8Nl+NtUVF0sA7MsXsP1UyJoMp4YLEuNSfAP+JcXn/tWtIaxVXM" crossorigin="anonymous"></script>
			{{ encore_entry_script_tags('app') }}

		{% endblock %}

	</head>
	<body>
		<div class="container p-3">

			<div class="row menu">
				<div class="col-6">
					<ul>
						<li>
							<a href="/">Bookstore
								<i class="bi bi-house"></i>
							</a>
						</li>

						<li>
							<a href="/livre">Livres
								<i class="bi bi-book-half"></i>
							</a>
						</li>
						<li>
							<a href="/auteur">Auteurs
								<i class="bi bi-person-circle"></i>
							</a>
						</li>

						<li>
							<a href="/genre">Genres
								<i class="bi bi-hash"></i>
							</a>
						</li>

						{% if app.user and app.user.roles[0]=="ROLE_ADMIN"%}
							<li>
								<a href="/admin">Administration
									<i class="bi bi-gear"></i>
								</a>
							</li>
						{% endif %}

					</ul>
				</div>

				<div class="col-2">
					{% if app.user %}
						<a class="login" href="/logout">
							<i class="bi bi-box-arrow-in-left"></i>Logout
						</a>
					{% endif %}

					{% if not app.user %}
						<a class="login" href="/login">Login
							<i class="bi bi-box-arrow-in-right"></i>
						</a>
					{% endif %}
				</div>
			</div>
			{% block body %}{% endblock %}
		</div>
	</body>
</html>

templates/index.html.twig
{% extends 'base.html.twig' %}

{% block title %}Bookstore
{% endblock %}

{% block style %}
	<link rel="stylesheet" href="{{ asset('css/style.css') }}">
{% endblock %}

{% block body %}


	<h1>Bookstore
		<i class="bi bi-book"></i>
	</h1>


	<table id="example" class="table table-dark table-striped table-hover" style="width:100%">
		<thead>
			<tr>
				<th>Isbn</th>
				<th>Titre</th>
				<th>Nombre_pages</th>
				<th>Date_de_parution</th>
				<th>Note</th>
				<th>Genres</th>
				<th>Auteurs</th>
			</tr>
		</thead>
		<tbody>
			{% for livre in livres %}
				<tr>
					<td>{{ livre.isbn }}</td>
					<td>{{ livre.titre }}</td>
					<td>{{ livre.nombrePages }}</td>
					<td>{{ livre.dateDeParution ? livre.dateDeParution|date('Y-m-d') : '' }}</td>
					<td>{{ livre.note }}</td>
					<td>
						<ul>
							{% for genre in livre.genres %}
								<li>
									{{genre}}
								</li>
							{% endfor %}
						</ul>
					</td>

					<td>
						<ul>
							{% for auteur in livre.auteurs %}
								<li>
									{{auteur}}
								</li>
							{% endfor %}
						</ul>
					</td>
				</tr>
			{% else %}
				<tr>
					<td colspan="7">no records found</td>
				</tr>
			{% endfor %}
		</tbody>
	</table>


	<script>
		$(document).ready(function () {
$('#example').DataTable();
});
	</script>

{% endblock %}